version: '3.3'
services:
  trackservice:
    image: trackimage
    container_name: trackcontainer
    build: usertrackservice/
    restart: always
    network_mode: host
    ports:
      - 8090:8090
    depends_on:
      - mongoservice

  mongoservice:
    image: mongo:3.2-jessie
    container_name: mongocontainer1
    ports:
      - 27017:27017
    network_mode: host

  userauthenticationservice:
    container_name: userauthenticationcontainer
    image: authenticationimage
    network_mode: host
    build: authenticationservice/
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice

  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"